<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PTAdmin 安装协议</title>
    <style>
        .content-body{
            word-wrap: break-word;
            margin: 1rem;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            line-height: 1.4;
        }
    </style>
</head>
<body class="content-body "><h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 18px;"><strong><span style="color: #444444; letter-spacing: 0pt;">用户须知</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt; text-align: justify;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;"><span style="font-family: 微软雅黑;">在使用重庆胖头网络技术有限公司（以下简称</span><span style="font-family: 微软雅黑;">“胖头”）服务或软件之前，请务必仔细阅读本协议，特别是免除或者限制责任的条款、管辖与法律适用的条款，以及关于开通或者使用第三方提供的某项服务的条款。重庆胖头网络技术有限公司的服务或者软件(以下简称“胖头软件”或“胖头服务”）的所有或任意部分一经复制、安装或使用，即表示您接受本协议所规定的全部条款及条件。您可与胖头直接订立另一书面协议，以补充或取代本协议的全部或任何部分。胖头软件只在遵守本协议各项条款的情况下供许可使用，并且不得出售。 胖头将不定时对本协议予以更新，更新内容一经正式发布即成为本协议不可分割的组成部分。在更新内容发布后继续使用胖头软件即表示您同意新的条款；如果您不同意新的条款，您应当卸载本软件及停止使用胖头软件、关闭您的胖头账号（重庆胖头网络技术有限公司*.pangtou.com上的账号），如果您是父母或监护人，请帮助您的未成年子女或者被监护人关闭他或她的胖头账户。 如果您未满18周岁，请在法定监护⼈的陪同下阅读本协议及其他上述协议，并特别注意未成年⼈适用条款。</span></span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">一、软件许可声明</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">1.1 许可授权</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;"><span style="font-family: 微软雅黑;">我们只是为用户（以下简称</span><span style="font-family: 微软雅黑;">“您”或“用户”）提供使用此软件的许可，并非将此软件所有权出售给您；在您同意所有条款之后，我们将通过许可证授予您拥有在特定设备中使用该软件的权利。许可期限到期或者终止后，在更新许可证之前，您可能无法使用胖头软件。经胖头及胖头同意的方式，您可变更安装和使用胖头的设备。</span></span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">1.2 许可证类型</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(1) 在许可期限内，胖头免费授予您一项非排他性和不可转让的许可，以使您能够在您拥有或控制的一台或多台支持设备上安装和使用胖头软件。软件包含胖头核心功能。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(2) 您仍可通过向胖头购买的方式就胖头提供的部分插件获得单独的使用许可授权。该部分授权同样适用本协议条款。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">1.3 除付费插件外，禁止对源代码进行加密和混淆。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">二、</span></strong><strong><span style="color: #444444; letter-spacing: 0pt;">胖头</span></strong><strong><span style="color: #444444; letter-spacing: 0pt;">的获取、安装、更新和卸载</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">2.1 您可直接从官网或者获得胖头授权的第三方处获取胖头软件。如果您从未经胖头授权的第三方处获取本软件或与本软件名称相同的安装程序，胖头无法保证该软件能够正常使用，并对因此给您造成的损失不承担责任。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">2.2 下载本软件后，您需要按照本软件提示的步骤正确安装。因您在安装过程中未按照提示步骤操作不当造成的损失，胖头不承担责任。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">2.3 为了完善用户体验，增强胖头软件的功能及性能，胖头将会不断努力开发新的功能，并为您不定期提供胖头软件更新。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">2.4 胖头软件可能会⾃动检测并提醒您安装更新，通过使用胖头软件，您同意胖头有权对胖头软件进行更新，或者对软件的部分功能进行改变或限制。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">2.5 胖头软件新版本发布后，旧版本的软件可能无法使用。胖头不保证旧版胖头软件继续可用及相应地为您服务，请您随时核对并下载最新版本。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">2.6 如您不再需要使用胖头，可以自行卸载本软件。您已获取的仍在有效期限内的许可证，不因卸载本软件而发生中止或终止，您为购买许可证所支付的费用，不因卸载本软件而退还。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">三、</span></strong><strong><span style="color: #444444; letter-spacing: 0pt;">胖头</span></strong><strong><span style="color: #444444; letter-spacing: 0pt;">账号</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">3.1 胖头账号是指胖头官网注册的账号，使用胖头产品需要注册绑定账号才可以正常使用。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">3.2 您须以真实身份注册开通胖头账号，并保证所提供的资料信息真实、完整、有效，且保证胖头可以通过您所填写的联系方式与您取得联系。注册胖头账号后，如果所提供的资料信息有所变更，应当及时更新。因资料信息没有及时变更导致的损失，胖头不承担任何责任。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">3.3 您所提供的信息适用于双方往来联系、书面文件送达及争议解决时法律文书送达。因您提供的联系方式和联系信息错误而无法直接送达的自交邮后第7日视为送达。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">3.4 您应对您的账号负责，只有您本人可以使用您的胖头账号，该账号不可转让、不可赠予、不可继承。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">3.5 您应妥善保管并正确、安全地使用账号及密码，对使用该账号及密码进行的一切操作负完全的责任。如您发现有他人冒用或盗用您的账户及密码或任何其他未经合法授权之情形时，应立即以有效方式通知胖头，要求胖头暂停相关服务。同时，胖头应对您的请求做出及时响应，您应理解在此之前，胖头对您的账号中已执行的指令及所导致的您的损失不承担任何责任。对于未尽上述保管义务导致账号密码遗失、账号被盗等情形而给您权利造成损害的，您应自行承担一切由此产生的损失。胖头应积极地采取技术与管理等合理措施保障用户账号的安全、有效。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">四、数据信息保护</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.1 胖头致力于保护您的信息安全，并为此采取合理的预防措施。除法律法规规定的情形和您的许可外，胖头不会向第三方公开、透露您的个人信息。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.2 在胖头软件安装和使用过程中，本软件将向胖头发送本软件及安装本软件的支持设备的信息，该信息包括本软件的版本、语言、支持设备的IP地址、硬件配置信息。胖头通常使用该信息以确认您使用本软件的最新版本、允许您下载和安装适用于该支持设备的更新版本，而不会作为用于识别您的个人信息；如果您是注册用户，胖头将使用该信息以确保支持设备与胖头服务的交互，您可通过本软件内的设置限制或在特定情形下限制该交互技术。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.3 为确保使用符合行业标准的内容加密技术来保护您的支持设备与胖头之间的信息传输，胖头可能将使用数字证书。为保护上述传输的安全性，您无法禁用该数字证书。通过使用本软件，您特此同意分享该信息及该交互技术。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.4 您在使用本软件或使用胖头服务的过程中，可能需要填写一些必要的信息。若国家法律法规或政策有特殊规定的，您需要填写真实的身份信息。若您填写的信息不完整，则无法使用本软件或胖头服务，或者在使用过程中受到限制。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.5 为创建和支持您的账户、向您提供方便又个性化的服务和活动，以及改进本软件的功能和可用性，胖头有权收集您某些必要的信息并在上述目的范围内使用和处理。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.6 在法律允许的范围内，胖头可能收集、使用、处理非识别性数据，以改善本软件或胖头服务，更好地满足您的需求。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.7 胖头在使用过程中不会收集、传输、存储其安装载体中的数据，您需要自行负责您的数据安全与备份。您理解并同意胖头无法提供找回丢失数据等服务。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.8 您理解并同意本软件的开发是一个持续开发过程，您及其他用户因此而受益。为促进本软件的持续开发，您可以向胖头提供关于使用、改进或应用本软件的建议、文件、材料或其他数据（简称“贡献”）。您充分了解并同意胖头可能在本软件和相关产品或服务上使用贡献。除非胖头和您针对任何贡献签署书面文件或本协议另有约定，您授予胖头不可撤销的、永久的、非排他的、世界范围内的、免费的许可，可以在开发、示范、展示、许可、修改、复制、分发和出售本软件或相关产品和服务时披露、使用和纳入。同时请确保您的反馈不包含您或者第三方的机密和著作权信息。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.9 您可阅读胖头网站上发布的《隐私声明》进一步了解胖头会如何收集、使用、存储和保护您的个人信息及您享有何种权利。该《隐私政策》可能会不时更新，在上述更新发布后继续使用本软件或胖头服务即表示您同意新的条款。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">4.10 如果您未满18周岁，您在使用本软件前须取得法定监护人的书面同意。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">五、用户使用规范</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">5.1 除非法律允许、本协议另有规定或胖头书面许可外，您不得从事下列行为：</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(1) 出租、出借、许可、出售、复制、修改或传播本软件，或基于胖头创造衍生作品，或促使或允许他人作上述行为；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(2) 修改或删除本软件及其副本或任何第三方软件上关于胖头或第三方的版权声明、商标或其他知识产权声明；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(3) 以任何形式或为任何目的，直接或间接对本软件进行修改、翻译、反向工程、反向汇编、反向编译、转换为其他编程语言或者以其他方式尝试发现本软件的源代码或由本软件产生的内在数据文件，或对本协议项下获取的任何软件或固件进行任何类似操作；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(4) 对本软件或者本软件运行过程中释放到任何终端内存中的数据、软件运行过程中客户端与服务器端的交互数据以及本软件运行所必需的系统数据，予以复制、修改、增加、删除、挂接运行或创作任何衍生作品，包括但不限于使用插件、外挂或未经胖头授权的第三方工具接入本软件和相关系统；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(5) 通过修改或伪造本软件运行中的指令、数据，增加、删减、变动本软件的功能或运行效果，或者将用于上述用途的软件、方法进行运营或向公众传播，无论这些行为是否为商业目的；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(6) 通过非胖头开发、授权的第三方软件、插件、外挂、系统，登录或使用本软件及胖头服务，或制作、发布、传播上述工具；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(7) 自行、授权他人或利用第三方软件对本软件及其组件、模块、数据等进行干扰；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(8) 任何危害本软件或利用本软件危害计算机网络安全的行为；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(9) 以意图规避胖头服务条款、违反相应法律法规的方式或超出正常使用范围而使用本软件；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(10) 通过本软件或胖头服务向他人发送、诱导或煽动他人发送大量信息；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(12) 其他未经胖头明示授权、许可或违反本协议的行为。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">5.2 在使用本软件或胖头服务时，您不得从事下列行为，或为下列行为提供帮助：</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(1) 上传、储存、发布、传送、传播或使用违反国家法律、危害国家安全统一、社会稳定、公序良俗、社会公德以及侮辱、诽谤、淫秽、暴力的内容；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(2) 上传、储存、发布、传送、传播或使用侵害他人名誉权、肖像权、知识产权、商业秘密等合法权利的内容；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(3) 上传、储存、发布、传送、传播或使用涉及他人隐私、个人信息或资料的内容；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(4) 发布、传送、传播骚扰、广告信息及垃圾信息；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(5) 虚构事实、隐瞒真相以误导、欺骗他人；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(6) 发布、传送、传播广告信息及垃圾信息；或</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(7) 从事其他违反法律法规、政策及公序良俗、社会公德等的行为。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">5.3 您在使用卖方产品时不侵犯任何第三方合法权益，不使用本软件上传、储存、发布、传送、传播或使用包含以下内容的信息：</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(1) 侵害他人名誉权、肖像权、知识产权、商业秘密等合法权利；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(2) 侵犯他人隐私、个人信息、个人资料；或</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(3) 其他侵犯其他用户或第三方合法权益。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">5.4 您应妥善保管登录和使用本软件和服务的信息及密码，不向他人透露，并对您未妥善保管账户信息及密码所受到的损失承担全部责任。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">六、用户行为责任</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">6.1 您充分了解并同意，您必须为自己使用本软件及胖头服务的一切行为负责，包括您利用本软件或胖头服务储存、发布、传送、传播的任何内容以及由此产生的任何后果。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">6.2 如胖头发现或收到他人举报您有违反本协议或相关法律法规的行为，我们将采取包括但不限于终止授权许可、停止技术支持、向有关部门移交线索、追究法律责任等措施。您同意并确认这是胖头为维护健康良好的网络环境而采取的必要措施，若由于胖头按照前述约定采取措施而对您产生影响或任何损失的，您同意不追究胖头的任何责任或不向胖头主张任何权利。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">6.3 您将就任何第三方因您违反上述条款而遭受的所有损害承担责任，同时如胖头因您的违反遭受损失，您也应当赔偿胖头的相关损失。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">七、第三方软件及技术</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">7.1 胖头软件可能会使用第三方软件或技术（例如开源的开发框架及公共插件等等），这种使用已获得合法授权。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">7.2 胖头为您提供第三方应用购买和下载服务。第三方应用由第三方开发者提供，使用时可能会向您请求权限。您在购买、下载和使用第三方提供的应用之前，建议您详细了解该应用可能会获取的权限和第三方的隐私声明和政策等。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">7.3 您同意使用第三方应用时，您将与应用开发者订立合同（下称“第三方协议”）。胖头不是您与第三方应用提供商订立的第三方协议中的一方，因此我们建议您仔细阅读第三方协议及第三方隐私政策。胖头无权也没有义务控制或审查第三方应用提供商所提供产品或服务的内容，对于您在使用此类第三方产品与服务时遭受的权益侵犯，胖头不承担任何责任。胖头不对任何第三方产品或服务的安全性、准确性、稳定性或其他不确定的风险负责，也不为第三方在胖头提供的任何内容、广告、产品、服务或其他信息作出任何形式的背书。若您不遵守第三方协议或第三方隐私政策，第三方可能对您采取法律行动。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">7.4 通过胖头购买、下载和使用第三方应用与服务导致的任何争议由第三方服务提供商解决，如因第三方服务的中断、暂停、数据泄露或其他问题引起的争议及损害，胖头对此不承担任何责任。胖头不为第三方软件或技术提供任何客户支持。若您需要支持，需联系第三方服务提供商。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">7.5 各第三方服务提供商为其产品、服务、内容及所作保证承担全部责任。若出现争议，以第三方服务提供商的产品或服务保证或第三方协议的约定为准。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">7.6 您理解并同意，胖头将不定期更新胖头软件，增强胖头软件的功能及性能，无法保证您所购买和使用的第三方应用适用于胖头所有版本。如出现第三方应用与胖头不兼容的情形，您需要联系第三方开发者协商解决。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">7.7 您也许需要接受第三方开发者的协议和收费才能下载和使用他们的应用。您特此确认并知悉，开发者可以保留调整应用价格的权利，并在您购买相应的应用之前适时告知您。新的价格生效后，您需要接受新调整的价格才能够继续使用应用。如果您不同意应用调整后的价格，您有权停止使用本服务。您将需要根据任何适用的相关法律要求纳税。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">八、免责申明</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.1 您明确认可并同意，您使用胖头软件需自行承担风险，并承担有关质量满意度、性能、准确性及结果等方面的全部风险。您进一步理解并同意，根据目前行业技术发展水平，尚无法保证完全不发生故障或系统没有漏洞及程序不会出错，并可能因此产生人身或财产损害的风险，您在使用胖头时应采取必要的措施保障安全性，包括但不限于安全防护措施、数据备份措施等。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.2 胖头向您保证，胖头尽合理商业努力保障卖方产品的正常运行及实质上符合本软件适用的行业标准。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.3 您理解并同意，如胖头或其许可方违反上述保证，我们的责任仅限于为您修补或更换本软件。胖头可能会要求您向胖头或其授权方返还或证明本软件的损坏。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.4 除本协议第8.3条明确约定外，在法律允许的最大范围内，胖头明确否认任何形式的所有明示或暗示的保证及条件，包括但不限于，适销性、针对特定用途的适用性和无侵权的默示保证和条件。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.5 安装胖头软件可能影响第三方软件、应用软件或第三方服务的可用性，您在安装、使用胖头的全过程中应自行采取必要的措施以避免对您造成损失，包括但不限于使用环境测试、数据备份等。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.6 胖头不保证本软件满足您的所有需求、本软件的运行不间断、安全或无错误或本软件的所有错误均可被纠正。并且，胖头不对因下列情况引起的缺陷或错误负责：</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(1) 胖头在官网公告之系统停机维护期间；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(2) 除胖头以外的一方修改、错误使用或损坏本软件；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(3) 您未能安装胖头提供的所有的漏洞修补程序或其他缺陷修复程序；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(4) 未根据本协议及本软件指示或要求正确使用本软件；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(5) 第三方个人电脑、设备、网络或软件的缺陷或错误，或用户操作失误；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(6) 因网络服务特性而特有的情况，包括但不限于基础网络运营商故障、计算机或互联网技术缺陷、互联网覆盖范围限制、计算机病毒、黑客攻击、网络设备或技术提供商的服务延迟或障碍等。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.7 胖头不对任何非胖头的产品或服务作出保证及承担责任，包括但不限于第三方软件或硬件、互联网连接或计算机网络。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.8 互联网传输无法保证100%的安全，您确认具有互联网安全知识，能够自行承担信息传输过程中可能产生的风险。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.9 胖头不对因不可抗力造成的本软件或胖头服务的中断或故障承担责任，不可抗力包括但不限于自然灾害、战争行为、恐怖活动、骚乱、革命、罢工等社会因素、立法变化、政策修改、政府行为及命令、电信部门技术调整等不能预见、不能避免并不能克服的客观情况。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.10 在任何情况下，胖头不因您使用本软件或胖头服务所引起的或在任何方面与本软件或胖头服务有关的任何数据或个人或商业信息的丢失或损坏、任何意外的、间接的、特殊的、惩罚性的或附带的损害或请求（包括但不限于业务利润损失、业务中断、信息泄露、数据丢失、金钱损失或取得替代产品及服务的费用）承担责任。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.11 胖头向您免费提供软件许可，作为免费使用本软件的对价，除本协议另有约定外，胖头对本协议项下所有事项不承担责任，不论是合同、侵权或其他责任。本责任限制条款在本协议第8.3条软件保证救济不能完全弥补您的损失时仍然适用。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">8.12 您理解并同意，为了向您提供有效的服务，本软件会利用你终端设备的处理器和带宽等资源。本软件使用过程中可能产生数据流量费用，该费用由您承担。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">九、知识产权声明</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt; font-weight: 400;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">9.1 </span></span><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">您可以在协议规定的约束和限制范围内修改</span></span><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">胖头软件</span></span><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">源代码或界面风格，但无论何种情况，即：无论用途如何、是否经过修改或美化、修改程度如何，只要您使用</span></span><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">胖头软件</span></span><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">的任何整体或部分程序算法，都必须保留</span></span><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">胖头软件</span></span><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">的版权信息，且修改后的程序版权依然归</span></span><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">重庆胖头网络技术有限公司</span></span><span style="font-family: 微软雅黑; color: #555555; letter-spacing: 0pt; background: #ffffff;"><span style="font-family: 微软雅黑;">所有。</span></span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">9.2 胖头拥有对胖头官网以及本软件的所有权利或合法授权，包括但不限于著作权、商标权、专利权、商业秘密等知识产权，与本软件相关的所有信息内容（包括但不限于文本、图片、音频、视频、图表、标识、版面设计、排版方式、有关数据或电子文档等）及所有衍生作品（包括所有副本和相关资料）均受中国法律法规和相应国际条约的保护。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">9.3 在胖头协议有效期内，一方（“接受方”）必须对自另一方（“披露方”）所获知的任何非公开信息（包括但不限于技术信息、商业秘密、胖头协议内容）（统称“保密信息”）严格保密，在未事先取得披露方书面同意的情况下，不得向任何第三方披露。接收方同意应仅为履行本协议之目的使用保密信息，并采取必要合理的措施保护披露方的保密信息，接受方保证其因为工作需要接触保密信息的员工将对保密信息严格保密，且其已与其前述员工签订了相应的保密协议。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">十、开源许可</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">10.1 胖头支持行业技术学习、交流与发展，您被允许以自用为目的，对胖头向您公开的源代码实施以下行为：</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(1) 任意修改源代码；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(2) 创造衍生作品。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">10.2 您在实施本协议第10.1条的行为时，应当遵守以下要求：</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(1) 不得对胖头未公开的源代码实施该行为；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(2) 除以自用为目的外，不得以其他目的或形式实施该行为；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(3) 不得修改或删除任何关于胖头或第三方的版权声明、商标或其他知识产权声明；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(4) 不得以任何目的发表、发行、出租、出借、许可、出售或传播您修改后的源代码或衍生产品，或变相实施前述行为；</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(5) 不得以任何方式破坏胖头的授权许可机制（包括但不限于收集源代码后经营与胖头同类型、同性质服务等）</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">(6) 不得利用胖头、修改后的源代码或所创造的衍生作品实施任何违反法律法规，有悖公序良俗，危害网络安全，或者侵犯他人信息、人身或财产安全的行为。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">10.3 您应当对所修改的源代码或所创造的衍生作品的合法性、安全性、准确性、稳定性或其他不确定的风险负责。对于您所修改的源代码或所创造的衍生作品造成您自身或任何第三方损失的，胖头及胖头不承担任何责任，造成胖头损失的，您应当向胖头进行赔偿。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">十一、未成年人使用条款</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">11.1 若您未满18周岁，则为未成年人，您应当在监护人的监护、指导下阅读本协议以及使用胖头及相关服务。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">11.2 监护人应对未成年人使用胖头及服务时加以监督和引导。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">十二、法律管辖</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">12.1 本许可协议受中华人民共和国法律管辖并按该等法律解释，不适用法律冲突规则。如果具有合法管辖权的法院因故裁定本许可协议的任何条款或任何部分不可强制执行，则本许可的其余条款或部分仍具有完整法律效力和作用。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">12.2 双方发生争议时，所有因本协议引起的或与本协议有关的任何争议，双方应首先通过友好协商解决；如协商未果，任何一方可提交胖头住所地有管辖权的人民法院解决。</span></span></p>
<h5 style="margin: 7.5pt 0pt 2.5pt; font-family: 宋体; font-size: 10pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-size: 16px;"><strong><span style="color: #444444; letter-spacing: 0pt;">十三、其他</span></strong></span></span></h5>
<p class="MsoNormal" style="margin: 0pt 0pt 1.5pt; font-family: Calibri; font-size: 10.5pt; font-weight: 400; text-indent: 0pt; padding: 0pt; line-height: 1.5;"><span style="font-size: 14px;"><span style="font-family: 微软雅黑; color: #666666; letter-spacing: 0pt;">13.1 您使用胖头软件即视为您已阅读并同意受本协议的约束。胖头有权在必要时修改本协议条款。您可以在胖头软件的最新版本中查阅相关协议条款。本协议条款变更后，如果您继续使用胖头软件，即视为您已接受修改后的协议。如果您不接受修改后的协议，应当停⽌使用胖头软件。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: Calibri; font-size: 10.5pt; font-weight: 400; line-height: 1.5;"><span style="font-size: 14px;">&nbsp;</span></p><script>document.addEventListener && document.addEventListener("click", function(e) {for (var elm = e.target; elm; elm = elm.parentNode) {if (elm.nodeName === "A" && !(e.metaKey)) {e.preventDefault();}}}, false);</script> </body>
</html>